### ISSUE TITLE
--out CLI option does not work

### ISSUE THREAD

**Issue by sylvainpolletvillard** [goto-bus-stop/split-require#14]
I tried to use the `--out` CLI option as described in the README: https://github.com/goto-bus-stop/split-require#--out

`browserify app/index.js -p [ split-require --out dist ]`
`browserify app/index.js -p [ split-require --out ./dist/ ]`

Nothing worked. Also I checked the source and cannot find the `out` option being used. The only option In found is `dir`: https://github.com/goto-bus-stop/split-require/blob/9962346694ad442105b07d98843c56c186d5866a/plugin.js#L120

I tried with the `--dir` option and it worked !

`browserify app/index.js -p [ split-require --dir ./dist/ ]`

Do you need to update the docs ?

**Comment by goto-bus-stop** [comment]
oops, i renamed it to `--out` in docs in https://github.com/goto-bus-stop/split-require/commit/003deb06769e65821f85dd0cd543e4590abd8442 because it was no longer just referring to an output directory, but i didn't change the code to match. fixed in https://github.com/goto-bus-stop/split-require/commit/91be7ae4d2e91de8a698b38f2eca9d1fcd4f053e (📦 2.1.1); the `--dir` option will keep working as well of course. thanks for the report!

**Comment by sylvainpolletvillard** [comment]
Thanks for the super fast fix ⚡️
